In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

In [3]:
ring = pd.read_csv("wang_ring2.csv")
watch = pd.read_csv("watch_example.csv")
watch.drop("sub_index", axis=1, inplace=True)

In [4]:
ring.dtypes

timestamp      str
rri_ms       int64
asc_area     int64
desc_area    int64
motion       int64
dtype: object

In [5]:
watch.dtypes

record_time      str
rri            int64
area_up        int64
area_down      int64
motion         int64
dtype: object

In [6]:
watch.head(5)

           record_time  rri  area_up  area_down  motion
0  2025-03-12 09:04:25  750        7        212     938
1  2025-03-12 09:04:25  610        5        210     375
2  2025-03-12 09:04:26  760        3        208      57
3  2025-03-12 09:04:27  870        1        206      40
4  2025-03-12 09:04:28  900        0        204       7

In [7]:
ring.head(5)

             timestamp  rri_ms  asc_area  desc_area  motion
0  2026-05-26 11:15:43    1159       126        428     142
1  2026-05-26 11:15:44    1114       125        413       0
2  2026-05-26 11:15:45    1069       125        398       0
3  2026-05-26 11:15:46    1024       124        383       0
4  2026-05-26 11:15:47     980       124        368       0